### ISSUE TITLE
Progress listeners break after logging out and back in

### ISSUE THREAD

**Issue by RasmusAntons** [Gaming32/bingo#22]
If a player leaves the server and rejoins during a game, their goal progress is no longer updated (except once immediately after rejoining).

I don't exactly know why that happens, but my guess is that Minecraft doesn't allow multiple listeners for the same player on the same criterion. I tried around a bit and [removing the listeners when a player quits](https://github.com/RasmusAntons/bingo/commit/1a59587790f4468653090add453cc4e25c2cb0b3) solves this issue.

**Comment by Gaming32** [comment]
Can you PR this fix?

**Comment by RasmusAntons** [comment]
Yes, I wasn't sure if that's how you want to implement it.
