### ISSUE TITLE
Bingo not registering

### ISSUE THREAD

**Issue by JojoXci** [Gaming32/bingo#24]
So when we have a square it does not register as completed, but it does show progress. For example "collect 4 raw cod" does show the bar and progress but when completed does not register it as completed. Also tasks like "place a cactus in a flower pot" do not work

Version: 1.21
We launch via modrinth
Server: shockbyte fabric

**Comment by RasmusAntons** [comment]
Goals work for me, are you sure you're on a team that's part of the game?

**Comment by JojoXci** [comment]
> Goals work for me, are you sure you're on a team that's part of the game?

Yes, we made 2 teams (for 2 people)

**Comment by JojoXci** [comment]
I'm sorry, we didn't join the team after we made them...
