### ISSUE TITLE
Invalid Player Data when joining singleplayer world

### ISSUE THREAD

**Issue by Qsta981** [Gaming32/bingo#7]
Whenever I attempt to create a singleplayer world with this mod, it gives me the error: Connection Lost-Invalid Player Data. I play with many mods. The profile is linked below.

Modlist:
allarrowsinfinityfix-1.5-fabric-mc1.20.jar
animatica-0.6+1.20.jar
appleskin-fabric-mc1.20.2-2.5.1.jar
architectury-10.0.17-fabric.jar
AttributeFix-Fabric-1.20.2-22.0.3.jar
Axiom-2.0.0-for-MC1.20.2.jar
axolotl-item-fix-1.1.7.jar
BetterAdvancements-Fabric-1.20.2-0.4.0.172.jar
betterbeds-1.3.0-1.19.3.jar
BetterF3-8.0.2-Fabric-1.20.2.jar
bettermounthud-1.2.2.jar
BetterPingDisplay-Fabric-1.20.2-1.1.1.jar
BetterRottenFlesh-fabric-1.20.X.jar
bettersafebed-fabric-1.20-9.jar
betterspawnercontrol-1.20.2-4.4.jar
betterstats-3.7.1+fabric-1.20.2.jar
BetterThirdPerson-Fabric-1.20-1.9.0.jar
bingo-1.0+fabric.jar
Boat-Item-View-Fabric-1.20.1-0.0.5.jar
BoatBreakFix-Universal-1.0.2.jar
bobby-5.1.0+mc1.20.2.jar
Bookshelf-Fabric-1.20.2-21.0.14.jar
borderless-mining-1.1.9+1.20.2.jar
capes-1.5.3+1.20.2-fabric.jar
carpet-addons-not-found-1.20.2-1.3.1.jar
carpet-extra-1.20.2-1.4.118.jar
carpet-tis-addition-mc1.20.2-v1.55.0.jar
carpetgamerules-mc1.20.2-v2.2.0.jar
CarpetTCTCAddition-all-2.2.212+46263e3-stable.jar
chat_heads-0.10.31-fabric-1.20.2.jar
chesttracker-2.2.3+1.20.2.jar
chunksfadein-v1.0.2-1.20.2.jar
CITResewn-1.1.3+1.20.jar
cloth-config-12.0.119-fabric.jar
collective-1.20.2-7.30.jar
continuity-3.0.0-beta.4+1.20.2.jar
Controlling-fabric-1.20.2-13.0.6.jar
CTM Selector-0.2.0+1.20.2.jar
cupboard-fabric-1.20.2-2.1.jar
Debugify-1.20.2+1.0.jar
DebugKeybind-6.0.0.jar
DisableCustomWorldsAdvice-4.1.jar
doubledoors-1.20.2-5.2.jar
durabilitytooltip-1.1.5-fabric-mc1.20.jar
dynamic-fps-3.3.3+minecraft-1.20.0.jar
e4mc-4.0.1+1.19.4-fabric.jar
eating-animation-1.20+1.9.5.jar
EnchantmentDescriptions-Fabric-1.20.2-18.0.6.jar
entity_model_features_fabric_1.20.2-1.2.3.jar
entity_texture_features_fabric_1.20.2-5.2.1.jar
entityculling-fabric-1.6.3-mc1.20.2.jar
Essential Dependencies.jar
essential_1-3-0-3_fabric_1-20-2.jar
ezmapdl-1.1.0-1.20.2.jar
fabric-api-0.91.6+1.20.2.jar
fabric-carpet-1.20.2-1.4.119+v230928.jar
fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
fabricskyboxes-0.7.3+mc1.20.2.jar
fabrishot-1.11.0.jar
fadeless-1.0.1.jar
farsight-fabric-1.20.2-4.1.jar
fastquit-3.0.0+1.20+.jar
ferritecore-6.0.1-fabric.jar
ForgeConfigAPIPort-v20.2.6-1.20.2-Fabric.jar
FpsReducer2-fabric-1.20.2-2.6.jar
freecam-fabric-1.2.1.1+1.20.jar
fsb-interop-1.3.6+mc1.20.2-build.52.jar
Gamma-Utils-1.7.17-mc1.20.2.jar
held-item-info-1.5.0.jar
ImmediatelyFast-Fabric-1.2.8+1.20.4.jar
immersive-portals-4.1.4-mc1.20.2-fabric.jar
indium-1.0.28+mc1.20.4.jar
InventoryProfilesNext-fabric-1.20.2-1.10.9.jar
invhud.fabric.1.20-3.4.19.jar
iris-mc1.20.2-1.6.14.jar
ItemsDisplayed - v1.2.1-1.20.2.jar
Jade-1.20.2-fabric-12.3.0.jar
jamlib-fabric-1.20.2-1.0.3+1.20.2.jar
jei-1.20.2-fabric-16.0.0.28.jar
justenoughbreeding-fabric-1.20.2-1.0.11.jar
JustEnoughProfessions-fabric-1.20.2-3.1.0.jar
keybind_fix-1.0.0.jar
lambdynamiclights-2.3.3+1.20.2.jar
language-reload-1.5.10+1.20.2.jar
libertyvillagers-2.0.0+fabric+1.20.2.jar
libIPN-fabric-1.20.2-4.0.1.jar
libreexpfix-0.2.4+1.20.2b11-BETA-fabric.jar
litematica-fabric-1.20.2-0.16.0.jar
lithium-fabric-mc1.20.2-0.12.0.jar
macos-input-fixes-1.6.jar
magiclib-all-0.7.398+fe2125a-stable.jar
main-menu-credits-1.1.2.jar
malilib-fabric-1.20.2-0.17.0.jar
mc-fix-hardcoded-lava-level-1.19.3-1.x_1.0.0.jar
minihud-fabric-1.20.2-0.28.0.jar
minitweaks-1.20.4-1.4.2.jar
mixintrace-1.1.1+1.17.jar
modelfix-1.14-fabric.jar
modernfix-fabric-5.10.1+mc1.20.2.jar
modmenu-2.0.17.jar
modmenu-8.0.0.jar
monsters-in-the-closet-1.0.3+1.20.jar
morechathistory-1.3.0.jar
moreculling-1.20.1-0.19.0.jar
music_control-1.6.4+1.20.2.jar
namepain-1.5.3 fabric-1.20.x.jar
Necronomicon-Fabric-1.4.1.jar
NoChatReports-FABRIC-1.20.2-v2.3.1.jar
notenoughanimations-fabric-1.7.0-mc1.20.2.jar
noxesium-1.1.1.jar
optigui-2.1.7.jar
paginatedadvancements-2.4.2.jar
puzzle-1.6.0+1.20.2.jar
recursive-resources-2.5.2+1.20.2.jar
reeses_sodium_options-1.7.0+mc1.20.2-build.97.jar
Resourcify (1.20.2+-fabric)-1.3.0.jar
rightclickharvest-fabric-4.1.3+1.20.2.jar
rrls-3.2.4+mc1.20.2-fabric.jar
Searchables-fabric-1.20.2-1.0.16.jar
shift-scroll-fix-1.0.1.jar
ShowMeWhatYouGot-1.20.2-1.2.0.jar
shulkerboxtooltip-fabric-4.0.7+1.20.2.jar
skinlayers3d-fabric-1.6.2-mc1.20.2.jar
sodium-extra-0.5.3+mc1.20.2-build.114.jar
sodium-fabric-mc1.16.5-0.2.0+build.4.jar
sodium-fabric-mc1.20.2-0.5.5.jar
stackrefill-1.20.2-4.2.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.2.jar
TimerHUD-3.1.0.jar
toggleableitemframes-4.1.0-1.20.4.jar
trade-cycling-fabric-1.20.2-1.0.7.jar
treeharvester-1.20.2-8.6.jar
tweakeroo-fabric-1.20.2-0.18.0.jar
veinmining-fabric-2.2.0+1.20.2.jar
villagerconfig-4.1.2+1.20.2.jar
whereisit-2.3.4+1.20.2.jar
xaeroarrowfix-fabric-1.3+1.20.jar
XaeroPlus-Fabric-1.20.2-28-WM1.37.8-MM23.9.7.jar
Xaeros_Minimap_23.9.7_Fabric_1.20.2.jar
xaeros-map-chest-tracker-integration-mc1.20.2-v2.0.1.jar
XaerosWorldMap_1.37.8_Fabric_1.20.2.jar
XaeroZoomout-Fabric-1.20-1.1.0.jar
yet-another-config-lib-fabric-3.3.0-beta.1+1.20.2.jar
yosbr-0.1.2.jar
Zoomify-2.13.0.jar

**Comment by Gaming32** [comment]
"Invalid Player Data" just means that something crashed in join code. Please post a log.

**Comment by Qsta981** [comment]
Yeah, I realized it is an issue with my other mods somehow.

**Comment by Qsta981** [comment]
Please close it as it is certainly not an issue with this mod.
